Test unique deploy
MyWishPlatform/new_sign pull request #1
Opened 2021-07-08 15:25 UTC by orionoiro

2021-07-08 15:34 UTC, yulian-khalitov requested changes

2021-07-08 15:34 UTC, yulian-khalitov commented on sign/views.py
> +            raise PermissionDenied
refactor ^=^

2021-07-08 15:56 UTC, yulian-khalitov requested changes

2021-07-08 15:56 UTC, yulian-khalitov commented on sign/views.py
> +    if tx_params.get('to'):
get('to', None)

2021-07-08 15:56 UTC, yulian-khalitov commented on sign/views.py
> +        if tx_params.get('contractId'):
get('child_id', None)

2021-07-08 15:59 UTC, orionoiro commented on sign/views.py
> +    if tx_params.get('to'):
@_@

2021-07-08 16:07 UTC, yulian-khalitov approved these changes

2021-07-12 12:09 UTC, yulian-khalitov approved these changes

2021-07-12 12:10 UTC, merged